# Generated by Django 3.2.5 on 2021-07-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210714_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('HOME', 'Home'), ('TECH', 'Technology'), ('BOOKS', 'Books'), ('BEAUTY', 'Beauty'), ('HEALTH', 'Health'), ('FASHION', 'Fashion'), ('STATIONARY', 'Stationary'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
