# Generated by Django 3.2.5 on 2021-07-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
    ]
